name: testytesttester
favicon: null
layout_spectrum: 0.8405944891273975
typography_spectrum: 0.14799639210104942
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5469318558461964
  lightness: 0.9246126958169043
  saturation: 0.48383920383639634
  rhythmicContrast: 0.2045148415490985
purpose: []
